#include "Config.h"

Config::Config(std::string filename)
{
  std::ifstream configFile(filename);
  std::string temp;
  std::getline(configFile, temp);
  std::getline(configFile, imagePath);
  std::getline(configFile, temp);
  std::getline(configFile, temp);
  std::getline(configFile, temp);
  rngSeed = atoi(temp.c_str());
  std::getline(configFile, temp);
  std::getline(configFile, temp);
  std::getline(configFile, temp);
  runsPerExperiment = atoi(temp.c_str());
  std::getline(configFile, temp);
  std::getline(configFile, temp);
  std::getline(configFile, logfile);
  std::getline(configFile, temp);
  std::getline(configFile, temp);
  std::getline(configFile, solfile);
  std::getline(configFile, temp);
  std::getline(configFile, temp);
  std::getline(configFile, temp);
  algorithmInd = atoi(temp.c_str());
  std::getline(configFile, temp);
  std::getline(configFile, temp);
  std::getline(configFile, temp);
  colorDistanceInd = atoi(temp.c_str());
  std::getline(configFile, temp);
  std::getline(configFile, temp);
  std::getline(configFile, temp);
  pixelClusterSize = atoi(temp.c_str());
  std::getline(configFile, temp);
  std::getline(configFile, temp);
  std::getline(configFile, temp);
  parentSelectionInd = atoi(temp.c_str());
  std::getline(configFile, temp);
  std::getline(configFile, temp);
  std::getline(configFile, temp);
  survivalSelectionInd = atoi(temp.c_str());
  std::getline(configFile, temp);
  std::getline(configFile, temp);
  std::getline(configFile, temp);
  terminationInd = atoi(temp.c_str());
  std::getline(configFile, temp);
  std::getline(configFile, temp);
  std::getline(configFile, temp);
  mu = atoi(temp.c_str());
  std::getline(configFile, temp);
  std::getline(configFile, temp);
  std::getline(configFile, temp);
  lambda = atoi(temp.c_str());
  std::getline(configFile, temp);
  std::getline(configFile, temp);
  std::getline(configFile, temp);
  parentTournamentSize = atoi(temp.c_str());
  std::getline(configFile, temp);
  std::getline(configFile, temp);
  std::getline(configFile, temp);
  survivalTournamentSize = atoi(temp.c_str());
  std::getline(configFile, temp);
  std::getline(configFile, temp);
  std::getline(configFile, temp);
  mutationRate = atoi(temp.c_str());
  std::getline(configFile, temp);
  std::getline(configFile, temp);
  std::getline(configFile, temp);
  numEvals = atoi(temp.c_str());
}